apiVersion: apps/v1
kind: Deployment
metadata:
  name: helixcore-api
spec:
  selector:
    matchLabels:
      app: helixcore-api
  replicas: 1
  template:
    metadata:
      labels:
        app: helixcore-api
    spec:
      containers:
        - name: helixcore-api
          image: dockertest
          imagePullPolicy: Never
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
