apiVersion: v1
kind: Service
metadata:
  name: helixcore-api-service
  labels:
    app: helixcore-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30050
    targetPort: 80
  selector:
    app: helixcore-api